name: First Workflow
on: workflow_dispatch
jobs: 
  first-job: 
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
          echo "Hello World!"
          echo "What should I ssy?"
      - name: Print questions
          echo "What do you want to know?"
      - name: Print goodbye
        run: |
          echo "Done - bye!"
          echo "Let's try somethiong new..."
    
