name: Next Workflow
on: workflow_dispatch
jobs:
  first-job: 
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
            echo "Hello again!"
            echo "How are you?"
            echo "What are you doin'?"
      - name: Print goodbye
        run: echo "All done. Bye."
